### PR TITLE
support for nvme devices

### PR DESCRIPTION
**Pull request by ClayStan**
support for nvme devices, and fix  /home partion not display problem.
I'm not good at C++, so this PR just fix the problem. If you want to make the code more elegant, you can make changes

### CODE REVIEW

**Comment by f35f22fan** [comment]
That's great, thank you. Merged.
I was wondering if the app can also mount and unmount NVME partitions (just so that I know that it's a problem or not)?
To mount an unmounted partition just click on it, to unmount right-click a mounted partition and click on "Unmount".

**Comment by f35f22fan** [comment]
I fixed also ReadStats() from ReadPaneItem.cpp, so hopefully nvme works fully fine. Created a new tag 1.0.4:
https://github.com/f35f22fan/Cornus/releases/tag/v1.0.4

**Comment by ClayStan** [comment]
OK~, I will test it

Brian Warner ***@***.***> 于2021年3月11日周四 下午7:05写道：

**Comment by ClayStan** [comment]
> That's great, thank you. Merged.
> I was wondering if the app can also mount and unmount NVME partitions (just so that I know that it's a problem or not)?
> To mount an unmounted partition just click on it, to unmount right-click a mounted partition and click on "Unmount".
not work to me , it can't show the partition which is umounted 
2021-03-12 09-40-20 的屏幕截图

**Comment by f35f22fan** [comment]
"not work to me , it can't show the partition which is unmounted"
I don't remember - did it show the unmounted nvme partitions before this
patch (v1.0.4)?

**Comment by ClayStan** [comment]
didn't show the unmounted nvme partitions before this
patch.
In fact , It never showed up

Brian Warner ***@***.***> 于2021年3月12日周五 上午10:17写道：

> "not work to me , it can't show the partition which is unmounted"
> I don't remember - did it show the unmounted nvme partitions before this
> patch (v1.0.4)?
>

**Pull request merged**
